title: FlowBridge
description: Bridging Ideas and Results
baseurl: ""
url: ""
markdown: kramdown
permalink: pretty
collections:
  resources:
    output: true
    permalink: /resources/:name/
  insights:
    output: true
    permalink: /insights/:name/
defaults:
  - scope:
      path: ""
      type: resources
    values:
      layout: resource
  - scope:
      path: ""
      type: insights
    values:
      layout: insight
